[package]
name = "soar-core"
version = "0.3.1"
description = "Core library for soar package manager"
authors.workspace = true
license.workspace = true
edition.workspace = true
repository.workspace = true
keywords.workspace = true
readme.workspace = true
categories.workspace = true

[dependencies]
blake3 = { version = "1.8.1", features = ["mmap"] }
chrono = { version = "0.4.40", default-features = false, features = ["now"] }
futures = { workspace = true }
image = { version = "0.25.6", default-features = false, features = ["png"] }
include_dir = "0.7.4"
nix = { version = "0.29.0", features = ["ioctl", "term", "user"] }
once_cell = "1.21.3"
rayon = { workspace = true }
regex = { workspace = true }
reqwest = { workspace = true }
rusqlite = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
soar-dl = { workspace = true }
squishy = { version = "0.3.2", features = ["appimage"] }
thiserror = "2.0.12"
toml = "0.8.20"
tracing = { workspace = true }
zstd = "0.13.3"
